In [1]:
import tensorflow as tf

In [2]:
tf.constant(1)

<tf.Tensor: id=0, shape=(), dtype=int32, numpy=1>

In [3]:
tf.constant(1.0)

<tf.Tensor: id=1, shape=(), dtype=float32, numpy=1.0>

In [4]:
tf.constant([True, False])

<tf.Tensor: id=2, shape=(2,), dtype=bool, numpy=array([ True, False])>

In [5]:
tf.constant('hello world')

<tf.Tensor: id=3, shape=(), dtype=string, numpy=b'hello world'>

In [6]:
with tf.device('cpu'):
    a = tf.constant([1])

In [7]:
a

<tf.Tensor: id=4, shape=(1,), dtype=int32, numpy=array([1])>

In [8]:
a.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [9]:
with tf.device('gpu'):
    b = tf.constant([1])

In [10]:
b

<tf.Tensor: id=5, shape=(1,), dtype=int32, numpy=array([1])>

In [11]:
b.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [12]:
aa = a.gpu()

Instructions for updating:
Use tf.identity instead.


In [13]:
aa.device

'/job:localhost/replica:0/task:0/device:GPU:0'

In [14]:
with tf.device('gpu'):
    bb = tf.constant([1.1])

In [15]:
bb.device

'/job:localhost/replica:0/task:0/device:GPU:0'

In [16]:
b = bb.cpu()

Instructions for updating:
Use tf.identity instead.


In [18]:
tf.identity(b).device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [19]:
tf.identity(bb).device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [20]:
bb

<tf.Tensor: id=7, shape=(1,), dtype=float32, numpy=array([1.1], dtype=float32)>

In [21]:
bb.device

'/job:localhost/replica:0/task:0/device:GPU:0'

In [22]:
tf.identity(a).device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [23]:
tf.identity(aa).device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [24]:
a.numpy()

array([1])

In [25]:
a.ndim

1

In [26]:
# 返回的是一个新建的tensor
tf.rank(a)

<tf.Tensor: id=11, shape=(), dtype=int32, numpy=1>

In [27]:
tf.rank(a).numpy()

1

In [28]:
tf.is_tensor(a)

True

In [29]:
a.dtype

tf.int32

In [30]:
import numpy as np
a = np.arange(5)
a.dtype

dtype('int32')

In [31]:
tf.is_tensor(a)

False

In [32]:
aa = tf.convert_to_tensor(a)

In [33]:
aa

<tf.Tensor: id=13, shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [34]:
tf.cast(aa,dtype=tf.float32)

<tf.Tensor: id=14, shape=(5,), dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>

In [35]:
a  = tf.range(5)

In [36]:
a

<tf.Tensor: id=18, shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [37]:
b = tf.Variable(a)

In [38]:
b.dtype

tf.int32

In [39]:
b.name

'Variable:0'

In [40]:
b.numpy()

array([0, 1, 2, 3, 4])

In [42]:
a = tf.ones([])

In [43]:
a

<tf.Tensor: id=27, shape=(), dtype=float32, numpy=1.0>

In [44]:
int(a)

1

In [45]:
float(a)

1.0

In [46]:
# 标量才可以
int(b)

TypeError: only size-1 arrays can be converted to Python scalars

In [47]:
y = tf.range(4)
tf.one_hot(y,depth=10)

<tf.Tensor: id=36, shape=(4, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [3]:
a = tf.ones([4,28,28,5])

In [6]:
tf.gather(a, [3,1], axis=0)

<tf.Tensor: id=8, shape=(2, 28, 28, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        ...,

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         ...,
         

In [7]:
tf.gather(a, [3,1], axis=1)

<tf.Tensor: id=11, shape=(4, 2, 28, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         ...,
         [1., 1., 1

In [8]:
tf.gather_nd(a, [[1],[2]])

<tf.Tensor: id=13, shape=(2, 28, 28, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        ...,

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         ...,
        

In [10]:
tf.gather_nd(a, [[1,1,1],[2,1,1]])

<tf.Tensor: id=18, shape=(2, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [11]:
tf.gather_nd(a, [1,1,1,1])

<tf.Tensor: id=20, shape=(), dtype=float32, numpy=1.0>

In [12]:
tf.gather_nd(a, [[1,1,1,1]])

<tf.Tensor: id=22, shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [13]:
tf.boolean_mask(a, mask=[True],axis=0)

ValueError: Shapes (4,) and (1,) are incompatible

In [14]:
tf.boolean_mask(a, mask=[True,False, False, False],axis=0)

<tf.Tensor: id=51, shape=(1, 28, 28, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        ...,

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         ...,
        

In [15]:
b = tf.ones([2,2,3])

In [16]:
tf.boolean_mask(b, mask=[[True,False],[True,True]])

<tf.Tensor: id=82, shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [18]:
c = tf.range(12)

In [19]:
d = tf.reshape(c, [2,2,3])

In [20]:
d

<tf.Tensor: id=92, shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])>

In [21]:
# 相当于[d[0,0].d[1,0],d[1,1]
tf.boolean_mask(d, mask=[[True,False],[True,True]])

<tf.Tensor: id=120, shape=(3, 3), dtype=int32, numpy=
array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])>

In [22]:
e = tf.reshape(tf.range(24), [2,3,4])

In [23]:
tf.boolean_mask(e, mask=[[True,False],[True,True]])

ValueError: Shapes (2, 3) and (2, 2) are incompatible

In [25]:
e

<tf.Tensor: id=126, shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

In [24]:
tf.boolean_mask(e, mask=[[True,False,True],[True,True,False]])

<tf.Tensor: id=155, shape=(4, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])>

In [26]:
a = tf.random.normal((4,3,2,1)) 

In [27]:
a.shape

TensorShape([4, 3, 2, 1])

In [28]:
tf.transpose(a).shape

TensorShape([1, 2, 3, 4])

In [29]:
tf.transpose(a, perm=[0,1,3,2]).shape
# perm指定维度，perm[a.shape[0],a.shape[1],a.shape[3],a.shape[2]]

TensorShape([4, 3, 1, 2])

In [30]:
a = tf.ones((2,3))

In [31]:
a + 1

<tf.Tensor: id=170, shape=(2, 3), dtype=float32, numpy=
array([[2., 2., 2.],
       [2., 2., 2.]], dtype=float32)>

In [33]:
a + tf.constant(1.0)

<tf.Tensor: id=173, shape=(2, 3), dtype=float32, numpy=
array([[2., 2., 2.],
       [2., 2., 2.]], dtype=float32)>

In [34]:
tf.constant([1.0]).shape

TensorShape([1])

In [35]:
a = tf.ones([2,4])

In [36]:
b = tf.ones([2,2])

In [37]:
a + b

InvalidArgumentError: Incompatible shapes: [2,4] vs. [2,2] [Op:AddV2] name: add/

In [38]:
a + tf.broadcast_to(b,[2,4])

InvalidArgumentError: Incompatible shapes: [2,2] vs. [2,4] [Op:BroadcastTo]

In [ ]:
tf.